### PR TITLE
Added handling of validateAuthority parameter

### PR DESCRIPTION
**Pull request by baSSiLL**

### CODE REVIEW

**Comment by baSSiLL** [comment]
Linked with issue #15

**Comment by mvertopoulos** [comment]
Thanks for this fix. Will update npm module as soon as possible.

**Comment by baSSiLL** [comment]
@mvertopoulos 
Just tried to update NPM module to v3.0.2. I see the changes in `lib/src/main.ts` but NO corresponding update in `dist/src/main.js`. Probably you forgot to recompile TS before assembling a new package.

**Comment by wizicer** [comment]
@mvertopoulos seems you forgot recompile before push to NPM

**Comment by mvertopoulos** [comment]
@baSSiLL @wizicer Indeed. Thanks for letting me know.

Recompiled and published v3.0.3 of the npm package.

**Comment by baSSiLL** [comment]
Thanks @mvertopoulos It works now

**Pull request merged**
